### ISSUE TITLE
Add automatic question numbering

### ISSUE THREAD

**Issue by dotemacs** [hmcts/hwf-publicapp#21]
For **Question X of Y** have something like:

``` ruby
"Question #{HomeController::ACTIONS.index(:benefit) + 1} of #{HomeController::ACTIONS.count + 1}"
```

on each form.

But for now, leave it, because I'll be missing some questions, so I'll set it manually.

**Comment by dotemacs** [comment]
@colinbruce we should work on getting this into the localisation somehow...

Maybe pass in: x,y, where x is 1 of 14 and the localisation string takes it and returns the appropriate line...

**Comment by colinbruce** [comment]
That could certainly work.  I was wondering about form_builder/helpers again...

```ruby
=question_header(scope: @benefit.i18n_scope, question: 1)
```
could render
```slim
h2.heading-large
  span.heading-secondary = t('breadcrumb', scope: scope, question: question)
  = t('text', scope: scope)

```
